# list of catholic_martyrs
catholic_martyrs = [
    "Achileo Kiwanuka",
    "Adolphus LudigoMukasa",
    "Ambrosius Kibuuka",
    "Anatoli Kiriggwajjo",
    "Andrew Kaggwa",
    "Antanansio Bazzekuketta",
    "Bruno Sserunkuuma",
    "Charles Lwanga",
    "Denis Ssebuggwawo Wasswa",
    "Gonzaga Gonza",
    "Gyavira Musoke",
    "James Buuzaabalyaawo",
    "John Maria Muzeeyi",
    "Joseph Mukasa",
    "Kizito",
    "Lukka Baanabakintu",
    "Matiya Mulumba",
    "Mbaga Tuzinde",
    "Mugagga Lubowa",
    "Mukasa Kiriwawanvu",
    "Nowa Mawaggali",
    "Ponsiano Ngondwe",
]

# list of Anglican martyrs
anglican_martyrs = [
    "Aaron Lubega",
    "Apollo Kivebulaya",
    "Eria Sebukyala",
    "Fredrick Kizza",
    "George Kizza",
    "James Hannington",
    "Janani Luwum",
    "Joseph Balikuddembe",
    "Kizito",
    "Mark Kakumba",
    "Matia Mulumba",
    "Nuhu Mbegu",
    "Robert Munyagayirwa",
    "Samwiri Mukasa",
    "Yefusa Namayanja",
    "Yohana Mukasa",
    "Yosefu Lugalama",
    "Yowana Kitaka",
    "Yowana Maria Mukasa",
    "Yowana Mukiibi",
    "Yusufu Lugalama",
    "Zakayo Lubega",
]
